sudo: required

language: C

compiler:
      - gcc

services:
      - docker

before_install:
    - docker info
    - docker build -t ntonjet/iidea-docker .

    - docker run -d -p 127.0.0.1:80:4567 ntonjet/iidea-docker /bin/bash -c "cd /opt/install-iidea"
    - docker ps -a
    - docker run ntonjet/iidea-docker /bin/bash -c "/opt/install-iidea/install-bellerophon"

#after_success:
#    - ./opt/llvm/install-clang

#script:  
    #- cd /opt/install-iidea/
    #- ./install-bellerophon 

#script:
  #- insert example script to run
