sudo: required

language: C

services:
      - docker

before_install:
    - docker info
    - docker build -t ntonjet/iidea-docker .

after_success:
    - ./opt/llvm/install-clang

#script:
#    - insert example script to run
