sudo: required

language: C

services:
      - docker

before_install:
    - docker info
    - docker build -t ntonjet/iidea-docker .
    - docker run -it -d ntonjet/iidea-docker /bin/bash    

#after_success:

script:
    - docker ps | grep -q ntonjet/iidea-docker
