sudo: required

language: C

compiler:
      - gcc

services:
      - docker

before_install:
    - docker info
    - docker build -t ntonjet/iidea-docker .
    - docker run -d --user root ntonjet/iidea-docker 

#after_success:
#    - ./opt/llvm/install-clang

script:  
    - cd /opt/install-iidea/
    - ./install-bellerophon 

#script:
  #- insert example script to run
